"""Flask microservice for retrieving merged GitHub pull requests. Generated by Claude Code; signed off by @jeffgdotorg."""

import os
from flask import Flask, request, jsonify, Response
from github_service import GitHubService
from formatters import DataFormatter

app = Flask(__name__)

# Initialize GitHub service
github_service = GitHubService()
formatter = DataFormatter()


@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint for OpenShift probes."""
    return jsonify({'status': 'healthy'}), 200


@app.route('/api/v1/prs', methods=['GET'])
def get_merged_prs():
    """
    Retrieve merged pull requests for a given repository and time period.

    Query Parameters:
        org (str): GitHub organization name
        repo (str): Repository name
        branch (str): Branch name to filter PRs merged into
        start_time (int): Start time as Unix epoch timestamp
        end_time (int): End time as Unix epoch timestamp
        format (str): Output format - 'json', 'yaml', or 'csv' (default: 'json')

    Returns:
        Merged PR data in the requested format
    """
    # Validate required parameters
    required_params = ['org', 'repo', 'branch', 'start_time', 'end_time']
    missing_params = [p for p in required_params if p not in request.args]

    if missing_params:
        return jsonify({
            'error': 'Missing required parameters',
            'missing': missing_params
        }), 400

    # Extract parameters
    org = request.args.get('org')
    repo = request.args.get('repo')
    branch = request.args.get('branch')
    output_format = request.args.get('format', 'json').lower()

    # Validate and parse timestamps
    try:
        start_time = int(request.args.get('start_time'))
        end_time = int(request.args.get('end_time'))
    except ValueError:
        return jsonify({
            'error': 'Invalid timestamp format',
            'detail': 'start_time and end_time must be Unix epoch integers'
        }), 400

    if start_time >= end_time:
        return jsonify({
            'error': 'Invalid time range',
            'detail': 'start_time must be less than end_time'
        }), 400

    # Validate format
    valid_formats = ['json', 'yaml', 'csv']
    if output_format not in valid_formats:
        return jsonify({
            'error': 'Invalid format',
            'detail': f'Format must be one of: {", ".join(valid_formats)}'
        }), 400

    # Fetch merged PRs
    try:
        pr_data = github_service.get_merged_prs(org, repo, branch, start_time, end_time)
    except Exception as e:
        return jsonify({
            'error': 'Failed to fetch PRs from GitHub',
            'detail': str(e)
        }), 500

    # Format response based on requested format
    try:
        if output_format == 'json':
            return jsonify(pr_data), 200
        elif output_format == 'yaml':
            yaml_output = formatter.to_yaml(pr_data)
            return Response(yaml_output, mimetype='application/x-yaml'), 200
        elif output_format == 'csv':
            csv_output = formatter.to_csv(pr_data)
            return Response(csv_output, mimetype='text/csv'), 200
    except Exception as e:
        return jsonify({
            'error': 'Failed to format response',
            'detail': str(e)
        }), 500


@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors."""
    return jsonify({'error': 'Endpoint not found'}), 404


@app.errorhandler(500)
def internal_error(error):
    """Handle 500 errors."""
    return jsonify({'error': 'Internal server error'}), 500


if __name__ == '__main__':
    port = int(os.getenv('PORT', 8080))
    app.run(host='0.0.0.0', port=port)
