"""Configuration management for the microservice. Generated by Claude Code; signed off by @jeffgdotorg."""

import os


class Config:
    """Base configuration."""

    # GitHub API token (required)
    GITHUB_TOKEN = os.getenv('GITHUB_TOKEN')

    # Server configuration
    PORT = int(os.getenv('PORT', 8080))
    HOST = os.getenv('HOST', '0.0.0.0')

    # Flask configuration
    DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
    TESTING = os.getenv('TESTING', 'False').lower() == 'true'


class DevelopmentConfig(Config):
    """Development configuration."""
    DEBUG = True


class ProductionConfig(Config):
    """Production configuration."""
    DEBUG = False


# Configuration dictionary
config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'default': ProductionConfig
}
