#!/bin/bash

# Example script to test the GitHub PR Hoover API
# Generated by Claude Code; signed off by @jeffgdotorg.
# Usage: ./example_request.sh [format]
# format: json (default), yaml, or csv

# Configuration
HOST="${API_HOST:-localhost:8080}"
FORMAT="${1:-json}"

# Example parameters - adjust these for your use case
ORG="jeffgdotorg"
REPO="claude-gh-pr-hoover"
BRANCH="main"

# Time range: Last 30 days from now
END_TIME=$(date +%s)
START_TIME=$((END_TIME - 2592000))  # 30 days in seconds

echo "Fetching merged PRs from ${ORG}/${REPO} on branch ${BRANCH}"
echo "Time range: $(date -r ${START_TIME}) to $(date -r ${END_TIME})"
echo "Format: ${FORMAT}"
echo ""

# Make the request
curl -s "http://${HOST}/api/v1/prs?org=${ORG}&repo=${REPO}&branch=${BRANCH}&start_time=${START_TIME}&end_time=${END_TIME}&format=${FORMAT}"

echo ""
