#!/bin/bash

# Example script to test the GitHub PR Hoover API
# Generated by Claude Code; signed off by @jeffgdotorg.
# Usage: ./example_request.sh [format]
# format: json (default), yaml, or csv

# Configuration
HOST="${API_HOST:-localhost:8080}"
FORMAT="${1:-json}"

# Example parameters - adjust these for your use case
ORG="RedHatInsights"
REPO="landing-page-frontend"
BRANCH="master"

# Time range: Last 30 days from now
END_TIME=$(date +%s)
START_TIME=$((END_TIME - 86400*30))  # 14 days in seconds

# Map format to Accept header
case "${FORMAT}" in
    yaml)
        ACCEPT_HEADER="application/x-yaml"
        ;;
    csv)
        ACCEPT_HEADER="text/csv"
        ;;
    *)
        ACCEPT_HEADER="application/json"
        FORMAT="json"
        ;;
esac

echo "Fetching merged PRs from ${ORG}/${REPO} on branch ${BRANCH}" >&2
echo "Time range: $(date -r ${START_TIME}) to $(date -r ${END_TIME})" >&2
echo "Format: ${FORMAT}" >&2
echo "" >&2

# Make the request
curl -s -H "Accept: ${ACCEPT_HEADER}" "http://${HOST}/api/v1/prs?org=${ORG}&repo=${REPO}&branch=${BRANCH}&start_time=${START_TIME}&end_time=${END_TIME}"

echo ""
