"""Data formatters for converting PR data to different output formats. Generated by Claude Code; signed off by @jeffgdotorg."""

import json
import csv
import yaml
from io import StringIO
from typing import List, Dict


class DataFormatter:
    """Utility class for formatting PR data into various formats."""

    @staticmethod
    def to_json(data: List[Dict]) -> str:
        """Convert PR data to JSON format."""
        return json.dumps(data, indent=2)

    @staticmethod
    def to_yaml(data: List[Dict]) -> str:
        """Convert PR data to YAML format."""
        return yaml.dump(data, default_flow_style=False, sort_keys=False)

    @staticmethod
    def to_csv(data: List[Dict]) -> str:
        """
        Convert PR data to CSV format.

        CSV format will have columns:
        prIdentifier, orgName, repoName, prId, creator, mergedBy, createdAt, mergedAt, reviewers
        """
        if not data:
            return ""

        output = StringIO()
        fieldnames = [
            'prIdentifier',
            'orgName',
            'repoName',
            'prId',
            'creator',
            'mergedBy',
            'createdAt',
            'mergedAt',
            'reviewers'
        ]

        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()

        # Each item in data is a single-key dict with PR identifier as key
        for pr_item in data:
            # Get the single key (PR identifier) and its value (PR data)
            pr_identifier = list(pr_item.keys())[0]
            pr_data = pr_item[pr_identifier]

            row = {
                'prIdentifier': pr_identifier,
                'orgName': pr_data['orgName'],
                'repoName': pr_data['repoName'],
                'prId': pr_data['prId'],
                'creator': pr_data['creator'],
                'mergedBy': pr_data['mergedBy'],
                'createdAt': pr_data['createdAt'],
                'mergedAt': pr_data['mergedAt'],
                'reviewers': ', '.join(pr_data['reviewers'])  # Join reviewers as comma-separated string
            }
            writer.writerow(row)

        return output.getvalue()
