"""GitHub API service for retrieving merged pull requests. Generated by Claude Code; signed off by @jeffgdotorg."""

import os
import requests
from datetime import datetime, timezone
from typing import List, Dict, Optional


class GitHubService:
    """Service to interact with GitHub REST API."""

    def __init__(self, token: Optional[str] = None):
        """Initialize GitHub service with authentication token."""
        self.token = token or os.getenv('GITHUB_TOKEN') or os.getenv('GITHUB_PERSONAL_ACCESS_TOKEN')
        if not self.token:
            raise ValueError("GitHub token must be provided via GITHUB_TOKEN or GITHUB_PERSONAL_ACCESS_TOKEN environment variable")

        self.base_url = "https://api.github.com"
        self.headers = {
            'Authorization': f'token {self.token}',
            'Accept': 'application/vnd.github.v3+json'
        }

    def get_merged_prs(
        self,
        org: str,
        repo: str,
        branch: str,
        start_time: int,
        end_time: int
    ) -> List[Dict]:
        """
        Retrieve merged pull requests for a given repository and time period.

        Args:
            org: GitHub organization name
            repo: Repository name
            branch: Branch name to filter PRs merged into
            start_time: Start time as Unix epoch timestamp
            end_time: End time as Unix epoch timestamp

        Returns:
            List of PR data objects
        """
        start_dt = datetime.fromtimestamp(start_time, tz=timezone.utc).isoformat()
        end_dt = datetime.fromtimestamp(end_time, tz=timezone.utc).isoformat()

        # Fetch all merged PRs to the specified branch
        prs = self._fetch_all_merged_prs(org, repo, branch, start_dt, end_dt)

        # Format results according to specification
        results = []
        for pr in prs:
            pr_id = pr['number']
            pr_identifier = f"{org}/{repo}#{pr_id}"

            # Get reviewers for this PR
            reviewers = self._get_pr_reviewers(org, repo, pr_id)

            # Parse timestamps
            created_at = int(datetime.fromisoformat(pr['created_at'].replace('Z', '+00:00')).timestamp())
            merged_at = int(datetime.fromisoformat(pr['merged_at'].replace('Z', '+00:00')).timestamp())

            # Each list element is a single-key object with the PR identifier as key
            results.append({
                pr_identifier: {
                    'orgName': org,
                    'repoName': repo,
                    'prId': pr_id,
                    'creator': pr['user']['login'],
                    'mergedBy': pr['merged_by']['login'] if pr.get('merged_by') else None,
                    'createdAt': created_at,
                    'mergedAt': merged_at,
                    'reviewers': reviewers
                }
            })

        return results

    def _fetch_all_merged_prs(
        self,
        org: str,
        repo: str,
        branch: str,
        start_dt: str,
        end_dt: str
    ) -> List[Dict]:
        """Fetch all merged PRs using pagination."""
        all_prs = []
        page = 1
        per_page = 100

        while True:
            url = f"{self.base_url}/repos/{org}/{repo}/pulls"
            params = {
                'state': 'closed',
                'base': branch,
                'sort': 'updated',
                'direction': 'desc',
                'per_page': per_page,
                'page': page
            }

            response = requests.get(url, headers=self.headers, params=params)
            response.raise_for_status()

            prs = response.json()
            if not prs:
                break

            # Filter for merged PRs within time range
            for pr in prs:
                if pr.get('merged_at'):
                    merged_time = datetime.fromisoformat(pr['merged_at'].replace('Z', '+00:00'))
                    start_time = datetime.fromisoformat(start_dt)
                    end_time = datetime.fromisoformat(end_dt)

                    if start_time <= merged_time <= end_time:
                        all_prs.append(pr)
                    elif merged_time < start_time:
                        # PRs are sorted by update time, if we've gone past our window, stop
                        return all_prs

            page += 1

        return all_prs

    def _get_pr_reviewers(self, org: str, repo: str, pr_number: int) -> List[str]:
        """Get list of reviewer usernames for a PR."""
        url = f"{self.base_url}/repos/{org}/{repo}/pulls/{pr_number}/reviews"

        response = requests.get(url, headers=self.headers)
        response.raise_for_status()

        reviews = response.json()

        # Extract unique reviewer usernames
        reviewers = set()
        for review in reviews:
            if review.get('user') and review['user'].get('login'):
                reviewers.add(review['user']['login'])

        return sorted(list(reviewers))
